// tools/embed-pregen.js — copies the Chunk Pregen behaviour pack (pregen/) into
// engine/pregen-pack.js, so Polis can build the .mcpack in the browser with no
// files to fetch (it works from GitHub Pages and from file:// alike).
// Run after changing anything in pregen/:   node tools/embed-pregen.js
// Section 2zb fails if the embedded copy and pregen/ differ.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'pregen');

export function collectPregen() {
  const files = {};
  const walk = (d, rel) => {
    for (const name of fs.readdirSync(d).sort()) {
      const p = path.join(d, name), r = rel ? rel + '/' + name : name;
      if (fs.statSync(p).isDirectory()) walk(p, r);
      else files[r] = fs.readFileSync(p);
    }
  };
  walk(dir, '');
  return files;
}

export function renderModule(files) {
  const manifest = JSON.parse(files['manifest.json'].toString('utf8'));
  const text = {}, binary = {};
  for (const [name, buf] of Object.entries(files)) {
    if (/\.(png)$/i.test(name)) binary[name] = buf.toString('base64');
    else text[name] = buf.toString('utf8');
  }
  return `// engine/pregen-pack.js — GENERATED by tools/embed-pregen.js from pregen/. Do not edit.
// The Chunk Pregen behaviour pack, embedded so Polis can hand it out.
export const PREGEN_VERSION = ${JSON.stringify(manifest.header.version.join('.'))};
export const PREGEN_TEXT = ${JSON.stringify(text, null, 0)};
export const PREGEN_BINARY = ${JSON.stringify(binary, null, 0)};
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = path.join(root, 'engine', 'pregen-pack.js');
  fs.writeFileSync(out, renderModule(collectPregen()));
  console.log(`wrote ${path.relative(root, out)}`);
}
