// tools/extract-rider.js — lift a minecart and the mob riding it out of a structure
// saved in game, and write them to engine/rider-templates.js.
//   node tools/extract-rider.js <endermantrap.mcstructure>
// The shipped pair came from a player's own enderman trap (a rail, a minecart, an
// enderman riding it): an enderman riding a minecart cannot teleport.
import { readFileSync, writeFileSync } from 'node:fs';
import { decodeTyped } from './nbt-typed.js';
const root = decodeTyped(new Uint8Array(readFileSync(process.argv[2]))).v;
const ents = root.structure.v.entities.v;
const id = (e) => e.v.identifier.v;
const cart = ents.find((e) => id(e) === 'minecraft:minecart');
const rider = ents.find((e) => e.v.UniqueID && cart.v.LinksTag && cart.v.LinksTag.v.some((l) => String(l.v.entityID.v) === String(e.v.UniqueID.v)));
if (!cart || !rider) throw new Error('no minecart with a rider in it');
// the rail it stands on: the structure's rail block, in the world
const num = (t) => (typeof t === 'number' ? t : t.v);       // (a typed list holds plain numbers)
const origin = Array.from(root.structure_world_origin.v, num);
const size = Array.from(root.size.v, num);
const pal = root.structure.v.palette.v.default.v.block_palette.v;
const bi = Array.from(root.structure.v.block_indices.v[0].v, num);
let railY = null;
for (let i = 0; i < bi.length; i++) { if (bi[i] < 0) continue; if (/rail/.test(pal[bi[i]].v.name.v)) railY = origin[1] + Math.floor(i / size[2]) % size[1]; }
const pos = (e) => Array.from(e.v.Pos.v, num);
// longs as strings (hydrate turns them back), every other tag as the game wrote it
const plain = (t) => {
  if (t.t === 4) return { t: 4, v: String(t.v) };
  if (t.t === 10) { const v = {}; for (const k of Object.keys(t.v)) v[k] = plain(t.v[k]); return { t: 10, v }; }
  if (t.t === 9) return { t: 9, et: t.et, keepEt: true, v: t.v.map(plain) };
  return { t: t.t, v: Array.isArray(t.v) ? t.v.slice() : t.v };
};
const out = {
  rider: id(rider), cartDy: pos(cart)[1] - railY, riderDy: pos(rider)[1] - railY,
  cart: plain(cart), riderNbt: plain(rider),
};
writeFileSync(new URL('../engine/rider-templates.js', import.meta.url),
`// engine/rider-templates.js — GENERATED by tools/extract-rider.js from a structure a
// player saved in Bedrock: a minecart on a rail and an enderman riding it (riding,
// it cannot teleport). Real entity NBT from the game. Do not edit by hand.
// Longs are stored as strings and turned into BigInt by hydrate().
export const MINECART_RIDER = ${JSON.stringify(out)};
`);
console.log('rider', out.rider, '| cart', out.cartDy, 'above its rail, rider', out.riderDy.toFixed(3), '| rider definitions:', rider.v.definitions.v.map((d) => d.v).join(' '), '| Persistent', rider.v.Persistent && rider.v.Persistent.v);
